name: mimseq-dev
channels:
  - bioconda
  - conda-forge
dependencies: # from https://github.com/bioconda/bioconda-recipes/blob/e4f33b5c94119efef67e6da9955f458c29ab40d9/recipes/mimseq/meta.yaml
  - r-base>=4.1
  - biopython>=1.79
  - matplotlib-base>=3.4.2
  - numpy>=1.21.1
  - pandas>=1.3.1
  - requests>=2.26.0
  - pybedtools>=0.8.2
  - pyfiglet>=0.8.post1
  - pysam>=0.16.0.1
  - seaborn-base>=0.11.1
  - statsmodels>=0.13.1
  - infernal>=1.1.4
  - blast>=2.10.1
  - gmap>=2018.03.20,<=2019.02.26
  - samtools>=1.11
  - bedtools>=2.30.0
  - r-ggplot2>=3.3.5
  - r-ggpol>=0.0.7
  - bioconductor-complexheatmap>=2.2.0
  - bioconductor-deseq2>=1.26.0
  - r-pheatmap>=1.0.12
  - r-calibrate>=1.7.7
  - r-gridextra>=2.3
  - r-plyr>=1.8.6
  - r-dplyr>=1.0.6
  - r-tidyverse>=1.3.0
  - r-devtools>=2.4.1
  - r-reshape2>=1.4.4